name: Upload Python Package to PyPI

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/build.yml

  build-package:
    name: Build Package
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Extract tag name
      id: tag
      run: echo "PKG_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> "$GITHUB_OUTPUT"

    - name: Update version in pyproject.toml
      run: >-
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.tag.outputs.PKG_VERSION }}/g" pyproject.toml

    - name: Build package
      run: python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/

  publish-to-test-pypi:
    name: Publish to TEST PyPI
    needs: build-package
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  publish-to-pypi:
    name: Publish to PRD PyPI
    needs: build-package
    runs-on: ubuntu-latest
    if: '!github.event.release.prerelease'
    environment: production
    permissions:
      id-token: write

    steps:
      - name: Fail if branch is not main
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "This workflow can only run on the main branch."
            exit 1
          fi

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      #- name: Publish package distributions to PyPI
      #  uses: pypa/gh-action-pypi-publish@release/v1
